### ISSUE TITLE
 Whether the model with ema needs bo be fixed in the validation phase —— “model(with ema).eval()”?

### ISSUE THREAD

**Issue by TIanCat** [fadel/pytorch_ema#3]

**Comment by fadel** [comment]
Hi,

I'm not sure I understood your question, but I have updated the example in README.md to show how the `store`/`restore` methods (contributed by @Zehui-Lin) can be used for validation without affecting training.

**Comment by TIanCat** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samuel Fadel"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 晚上8:41
收件人: "fadel/pytorch_ema"<pytorch_ema@noreply.github.com&gt;; 
抄送: "WangJian"<1090577307@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fadel/pytorch_ema]  Whether the model with ema needs bo be fixed in the validation phase —— “model(with ema).eval()”? (#3)





 
Hi,
 
I'm not sure I understood your question, but I have updated the example in README.md to show how the store/restore methods (contributed by @Zehui-Lin) can be used for validation without affecting training.
